# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799f48d657c439db0b4b889e09cf2548950cfe02e647bd492e0e3d932b77deeef8de9e482ea03c39788c466c1b3c9f65307d121565717c8070a907f38444e2f3

test:
  secret_key_base: 65daaa2466eba28b24f6c7ab75365bff4bd8346b9565985ec36bc6eaab49e80b75920959e5cca637539ae5f21b35e66cda62309e7d5c4fc4a8428e54a2bc2a26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
